<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Machine-Learning/blob/main/Day-28/Column-transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [10]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
df.isnull().sum()

# fever col has 10 missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2, random_state=2)

In [13]:
X_train.head()

    age  gender  fever   cough       city
35   82  Female  102.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
84   69  Female   98.0  Strong     Mumbai
44   20    Male  102.0  Strong      Delhi
73   34    Male   98.0  Strong    Kolkata

In [14]:
X_test.head()

    age  gender  fever   cough     city
83   17  Female  104.0    Mild  Kolkata
30   15    Male  101.0    Mild    Delhi
56   71    Male    NaN  Strong  Kolkata
24   13  Female  100.0  Strong  Kolkata
16   69  Female  103.0    Mild  Kolkata