<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Machine-Learning/blob/main/Day-32/Discretization(Bining).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

In [19]:
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [20]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [21]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [22]:
df.dropna(inplace=True)

In [23]:
df.shape

(714, 3)

In [24]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

## Train test split

In [25]:
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
X_test.head()

      Age   Fare
149  42.0  13.00
407   3.0  18.75
53   29.0  26.00
369  24.0  69.30
818  43.0   6.45

In [29]:
y_train.head()

328    1
73     0
253    0
719    0
666    0
Name: Survived, dtype: int64

## Decision Tree

In [30]:
clf = DecisionTreeClassifier()

In [31]:
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

In [32]:
accuracy_score(y_test, y_pred)

0.6293706293706294