<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Machine-Learning/blob/main/Day-26/Ordinal-and-Label-encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(5)

    age  gender   review education purchased
27   69  Female     Poor        PG        No
41   23    Male     Good        PG       Yes
13   57  Female  Average    School        No
2    70  Female     Good        PG        No
36   34  Female     Good        UG       Yes

In [5]:
df = df.iloc[:, 2:]

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Train test split

In [7]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2)

In [11]:
X_train

     review education
15     Poor        UG
18     Good    School
4   Average        UG
12     Poor    School
37  Average        PG
27     Poor        PG
2      Good        PG
29  Average        UG
3      Good        PG
28     Poor    School
45     Poor        PG
44  Average        UG
6      Good    School
7      Poor    School
38     Good    School
16     Poor        UG
36     Good        UG
21  Average        PG
48     Good        UG
46     Poor        PG
8   Average        UG
26     Poor        PG
35     Poor    School
32  Average        UG
5   Average    School
24  Average        PG
31     Poor    School
43     Poor        PG
13  Average    School
39     Poor        PG
49     Good        UG
11     Good        UG
40     Good    School
22     Poor        PG
10     Good        UG
30  Average        UG
34  Average    School
14     Poor        PG
33     Good        PG
9      Good        UG

In [12]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])